# -*- coding: utf-8 -*-
"""ancilliary_funcs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10o8rzSx1Ko1sXSHakGxh3_XNfDPi8DTU
"""

import pandas as pd
import numpy as np
import scipy.stats as stats
import matplotlib.pyplot as plt
import random

def descriptiva_frecuencia(dataframe, col):
  df_col = dataframe[col]
  df_col_dropna = df_col.dropna()
  df_gp = 0

  if isinstance(df_col, pd.Series) is True:
    if df_col.dtype != "object":
      
      desc = df_col_dropna.describe().round(3)
    
    else:
      df_gp = df_sample.groupby(col)[col].count()
  else:
    raise ValueError("Los datos no son del tipo pd.Series, selecciona otros.")

  return desc, df_gp

def null_list (dataframe, var, print_list = False):
  nvalues = []
  if isinstance(dataframe[var], pd.Series) is True:
    nvalues_countries = dataframe.loc[dataframe[var].isnull()]["cname"].unique()
    nvalues_count = dataframe.loc[dataframe[var].isnull()]["cname"].count()
    print("La cantidad de países sin información es:", nvalues_count, "y representan un", round((nvalues_count/len(dataframe))*100, 2), "% del total de países de la muestra.\n")
    
    if print_list is True:
      nvalues.append(nvalues_countries)
      print("Los países sin información en el caso de", var, "son:\n")
      print(nvalues)
    
    else:
      pass
      
  else:
    raise ValueError("Los datos no son del tipo pd.Series, selecciona otros.")

def graf_hist (true_df, sample_df, var, true_mean, sample_mean = False):
  sample_df_dropna = sample_df[var].dropna()
  true_mean_value = true_df[var].dropna().mean()
  sample_mean_value = sample_df_dropna.mean()
  
  if isinstance(sample_df_dropna, pd.Series) is True and sample_df_dropna.dtype != "object":
    plt.title("Histograma de variable")
    plt.hist(sample_df_dropna, color = "c", alpha = 0.5, density = False)
    if true_mean is True:
      plt.axvline(true_mean_value, color = "m", linestyle = "--", lw = 1)
      #plt.annotate("True mean", xy = (df_true_mean + 5, 0.06), color = "tomato", rotation = 60, ha = "center", size = 12)
    else:
      pass
    if sample_mean is True:
      plt.axvline(sample_mean_value, color = "b", linestyle = "--", lw = 1)
      #plt.annotate("Sample mean", xy = (df_sample_mean + 15, 0.06), color = "green", rotation = 60, ha = "center", size = 12)
    else:
      pass
  
  else:
    raise ValueError("Revisa la información proporcionada: selecciona una Serie del dataframe tipo float o integer.")

def graf_dotplot (true_df, sample_df, plot_var, plot_by, global_stat = False, statistic = "mean"):
  
  sample_df_dropna = sample_df[plot_var]
  true_mean_value = true_df[plot_var].dropna().mean()
  sample_mean_value = sample_df[plot_var].dropna().mean()
  sample_median_value = sample_df[plot_var].dropna().median()
  sample_mean_dotplot = round(sample_df.groupby(plot_by)[plot_var].mean(), 2)

  if isinstance(sample_df_dropna, pd.Series) is True and sample_df_dropna.dtype != "object":
    plt.title("Dotplot de variable")
    plt.plot(sample_mean_dotplot.values, sample_mean_dotplot.index, "s", color = "c")
    if global_stat is True:
      plt.axvline(true_mean_value, color = "b", linestyle = "--", lw = 1)
    else:
      pass
    if statistic == "mean":
      plt.axvline(sample_mean_value, color = "r", linestyle = "--", lw = 1)
    elif statistic == "median":
      plt.axvline(sample_median_value, color = "r", linestyle = "--", lw = 1)
    else:
      pass
    
  else:
    raise ValueError("Revisa la información proporcionada: selecciona una Serie del dataframe tipo float o integer.")